    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (3, 'Africa', 'Northern Africa', 'Maroc', 2021, 99.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (4, 'Africa', 'Sub-Saharan Africa', 'Botswana', 2021, 100.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (5, 'Africa', 'Sub-Saharan Africa', 'Ghana', 2021, 95.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (6, 'Africa', 'Sub-Saharan Africa', 'Kenya', 2021, 706.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (7, 'Africa', 'Sub-Saharan Africa', 'Maurice', 2021, 12.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (8, 'Africa', 'Sub-Saharan Africa', 'Namibie', 2021, 89.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (9, 'Africa', 'Sub-Saharan Africa', 'Afrique du Sud', 2021, 3255);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (11, 'Americas', 'Latin America and the Caribbean', 'Argentine', 2021, 308.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (12, 'Americas', 'Latin America and the Caribbean', 'Bahamas', 2021, 6.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (13, 'Americas', 'Latin America and the Caribbean', 'Barbade', 2021, 6.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (14, 'Americas', 'Latin America and the Caribbean', 'Belize', 2021, 11.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (15, 'Americas', 'Latin America and the Caribbean', 'Bolivie', 2021, 173.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (16, 'Americas', 'Latin America and the Caribbean', 'Brésil', 2021, 3844);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (17, 'Americas', 'Latin America and the Caribbean', 'Chili', 2021, 90.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (18, 'Americas', 'Latin America and the Caribbean', 'Colombie', 2021, 943.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (19, 'Americas', 'Latin America and the Caribbean', 'Costa Rica', 2021, 56.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (20, 'Americas', 'Latin America and the Caribbean', 'Dominique', 2021, 2.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (21, 'Americas', 'Latin America and the Caribbean', 'République dominicaine', 2021, 142.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (22, 'Americas', 'Latin America and the Caribbean', 'Équateur', 2021, 227.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (24, 'Americas', 'Latin America and the Caribbean', 'Grenade', 2021, 1.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (25, 'Americas', 'Latin America and the Caribbean', 'Guatemala', 2021, 545.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (26, 'Americas', 'Latin America and the Caribbean', 'Guyana', 2021, 13.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (27, 'Americas', 'Latin America and the Caribbean', 'Haïti', 2021, 112.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (28, 'Americas', 'Latin America and the Caribbean', 'Honduras', 2021, 329.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (29, 'Americas', 'Latin America and the Caribbean', 'Jamaïque', 2021, 133.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (30, 'Americas', 'Latin America and the Caribbean', 'Mexique', 2021, 4002);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (31, 'Americas', 'Latin America and the Caribbean', 'Nicaragua', 2021, 108.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (32, 'Americas', 'Latin America and the Caribbean', 'Panama', 2021, 43.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (33, 'Americas', 'Latin America and the Caribbean', 'Paraguay', 2021, 64.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (34, 'Americas', 'Latin America and the Caribbean', 'Pérou', 2021, 665.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (37, 'Americas', 'Latin America and the Caribbean', 'Sainte-Lucie', 2021, 8.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (39, 'Americas', 'Latin America and the Caribbean', 'Suriname', 2021, 7.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (40, 'Americas', 'Latin America and the Caribbean', 'Uruguay', 2021, 40.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (41, 'Americas', 'Northern America', 'Bermudes', 2021, 1.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (42, 'Americas', 'Northern America', 'Canada', 2021, 199.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (43, 'Americas', 'Northern America', 'États-Unis', 2021, 5.08);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (44, 'Asia', 'Central Asia', 'Kazakhstan', 2021, 140.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (45, 'Asia', 'Central Asia', 'Ouzbékistan', 2021, 179.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (48, 'Asia', 'Eastern Asia', 'Japon', 2021, 134.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (49, 'Asia', 'Eastern Asia', 'Mongolie', 2021, 43.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (51, 'Asia', 'South-eastern Asia', 'Myanmar', 2021, 1969);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (52, 'Asia', 'South-eastern Asia', 'Singapour', 2021, 2.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (53, 'Asia', 'Southern Asia', 'Inde', 2021, 17012);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (54, 'Asia', 'Western Asia', 'Arménie', 2021, 14.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (55, 'Asia', 'Western Asia', 'Azerbaïdjan', 2021, 69.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (56, 'Asia', 'Western Asia', 'Bahreïn', 2021, 1.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (57, 'Asia', 'Western Asia', 'Chypre', 2021, 7.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (59, 'Asia', 'Western Asia', 'Israël', 2021, 27.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (60, 'Asia', 'Western Asia', 'Jordanie', 2021, 31.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (61, 'Asia', 'Western Asia', 'Oman', 2021, 3.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (62, 'Asia', 'Western Asia', 'Qatar', 2021, 4.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (64, 'Asia', 'Western Asia', 'Turquie', 2021, 438.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (65, 'Asia', 'Western Asia', 'Émirats arabes unis', 2021, 10.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (66, 'Europe', 'Eastern Europe', 'Bulgarie', 2021, 28.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (68, 'Europe', 'Eastern Europe', 'Hongrie', 2021, 26.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (69, 'Europe', 'Eastern Europe', 'Pologne', 2021, 79.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (71, 'Europe', 'Eastern Europe', 'Roumanie', 2021, 76.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (74, 'Europe', 'Northern Europe', 'Danemark', 2021, 14.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (75, 'Europe', 'Northern Europe', 'Estonie', 2021, 4.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (76, 'Europe', 'Northern Europe', 'Finlande', 2021, 27.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (77, 'Europe', 'Northern Europe', 'Islande', 2021, 1.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (78, 'Europe', 'Northern Europe', 'Irlande', 2021, 7.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (79, 'Europe', 'Northern Europe', 'Lettonie', 2021, 36.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (80, 'Europe', 'Northern Europe', 'Lituanie', 2021, 22.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (81, 'Europe', 'Northern Europe', 'Norvège', 2021, 16.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (82, 'Europe', 'Northern Europe', 'Suède', 2021, 24.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (86, 'Europe', 'Southern Europe', 'Albanie', 2021, 12.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (87, 'Europe', 'Southern Europe', 'Bosnie-Herzégovine', 2021, 7.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (88, 'Europe', 'Southern Europe', 'Croatie', 2021, 14.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (89, 'Europe', 'Southern Europe', 'Grèce', 2021, 33.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (91, 'Europe', 'Southern Europe', 'Italie', 2021, 119.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (92, 'Europe', 'Southern Europe', 'Kosovo', 2021, 3.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (93, 'Europe', 'Southern Europe', 'Malte', 2021, 0.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (94, 'Europe', 'Southern Europe', 'Monténégro', 2021, 2.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (95, 'Europe', 'Southern Europe', 'Macédoine du Nord', 2021, 3.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (96, 'Europe', 'Southern Europe', 'Portugal', 2021, 25.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (97, 'Europe', 'Southern Europe', 'Serbie', 2021, 27.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (98, 'Europe', 'Southern Europe', 'Slovénie', 2021, 6.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (99, 'Europe', 'Southern Europe', 'Espagne', 2021, 97.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (100, 'Europe', 'Western Europe', 'Autriche', 2021, 40.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (101, 'Europe', 'Western Europe', 'Belgique', 2021, 11.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (102, 'Europe', 'Western Europe', 'France', 2021, 228.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (103, 'Europe', 'Western Europe', 'Allemagne', 2021, 337.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (104, 'Europe', 'Western Europe', 'Liechtenstein', 2021, 1.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (105, 'Europe', 'Western Europe', 'Pays-Bas', 2021, 38.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (106, 'Europe', 'Western Europe', 'Suisse', 2021, 25.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (107, 'Oceania', 'Australia and New Zealand', 'Australie', 2021, 49.0);
    INSERT INTO Feminicide (ID_Feminicide, Region, Subregion, ID_Pays, Year, Nombre_feminicides) VALUES (108, 'Oceania', 'Australia and New Zealand', 'Nouvelle-Zélande', 2021, 15.0);