INSERT INTO feminicide VALUES (2, 'Africa', 'Northern Africa', 'Égypte', 2021, 0.28);
INSERT INTO feminicide VALUES (3, 'Africa', 'Northern Africa', 'Maroc', 2021, 0.27);
INSERT INTO feminicide VALUES (4, 'Africa', 'Sub-Saharan Africa', 'Botswana', 2021, 4.25);
INSERT INTO feminicide VALUES (5, 'Africa', 'Sub-Saharan Africa', 'Ghana', 2021, 0.29);
INSERT INTO feminicide VALUES (6, 'Africa', 'Sub-Saharan Africa', 'Kenya', 2021, 1.29);
INSERT INTO feminicide VALUES (7, 'Africa', 'Sub-Saharan Africa', 'Maurice', 2021, 0.87);
INSERT INTO feminicide VALUES (8, 'Africa', 'Sub-Saharan Africa', 'Namibie', 2021, 3.32);
INSERT INTO feminicide VALUES (9, 'Africa', 'Sub-Saharan Africa', 'Afrique du Sud', 2021, 5.71);
INSERT INTO feminicide VALUES (11, 'Americas', 'Latin America and the Caribbean', 'Argentine', 2021, 0.67);
INSERT INTO feminicide VALUES (12, 'Americas', 'Latin America and the Caribbean', 'Bahamas', 2021, 1.7);
INSERT INTO feminicide VALUES (13, 'Americas', 'Latin America and the Caribbean', 'Barbade', 2021, 1.99);
INSERT INTO feminicide VALUES (14, 'Americas', 'Latin America and the Caribbean', 'Belize', 2021, 2.71);
INSERT INTO feminicide VALUES (15, 'Americas', 'Latin America and the Caribbean', 'Bolivie', 2021, 1.47);
INSERT INTO feminicide VALUES (16, 'Americas', 'Latin America and the Caribbean', 'Brésil', 2021, 2.27);
INSERT INTO feminicide VALUES (17, 'Americas', 'Latin America and the Caribbean', 'Chili', 2021, 0.49);
INSERT INTO feminicide VALUES (18, 'Americas', 'Latin America and the Caribbean', 'Colombie', 2021, 1.87);
INSERT INTO feminicide VALUES (19, 'Americas', 'Latin America and the Caribbean', 'Costa Rica', 2021, 1.09);
INSERT INTO feminicide VALUES (20, 'Americas', 'Latin America and the Caribbean', 'Dominique', 2021, 2.68);
INSERT INTO feminicide VALUES (21, 'Americas', 'Latin America and the Caribbean', 'République dominicaine', 2021, 1.34);
INSERT INTO feminicide VALUES (22, 'Americas', 'Latin America and the Caribbean', 'Équateur', 2021, 1.33);
INSERT INTO feminicide VALUES (23, 'Americas', 'Latin America and the Caribbean', 'Salvador', 2021, 2.04);
INSERT INTO feminicide VALUES (24, 'Americas', 'Latin America and the Caribbean', 'Grenade', 2021, 0.88);
INSERT INTO feminicide VALUES (25, 'Americas', 'Latin America and the Caribbean', 'Guatemala', 2021, 3.13);
INSERT INTO feminicide VALUES (26, 'Americas', 'Latin America and the Caribbean', 'Guyana', 2021, 1.65);
INSERT INTO feminicide VALUES (27, 'Americas', 'Latin America and the Caribbean', 'Haïti', 2021, 1.0);
INSERT INTO feminicide VALUES (28, 'Americas', 'Latin America and the Caribbean', 'Honduras', 2021, 3.52);
INSERT INTO feminicide VALUES (29, 'Americas', 'Latin America and the Caribbean', 'Jamaïque', 2021, 4.72);
INSERT INTO feminicide VALUES (30, 'Americas', 'Latin America and the Caribbean', 'Mexique', 2021, 3.07);
INSERT INTO feminicide VALUES (31, 'Americas', 'Latin America and the Caribbean', 'Nicaragua', 2021, 1.73);
INSERT INTO feminicide VALUES (32, 'Americas', 'Latin America and the Caribbean', 'Panama', 2021, 1.09);
INSERT INTO feminicide VALUES (33, 'Americas', 'Latin America and the Caribbean', 'Paraguay', 2021, 0.88);
INSERT INTO feminicide VALUES (34, 'Americas', 'Latin America and the Caribbean', 'Pérou', 2021, 2.07);
INSERT INTO feminicide VALUES (37, 'Americas', 'Latin America and the Caribbean', 'Sainte-Lucie', 2021, 4.8);
INSERT INTO feminicide VALUES (40, 'Americas', 'Latin America and the Caribbean', 'Uruguay', 2021, 1.18);
INSERT INTO feminicide VALUES (41, 'Americas', 'Northern America', 'Bermudes', 2021, 1.39);
INSERT INTO feminicide VALUES (42, 'Americas', 'Northern America', 'Canada', 2021, 0.52);
INSERT INTO feminicide VALUES (43, 'Americas', 'Northern America', 'États-Unis', 2021, 1.49);
INSERT INTO feminicide VALUES (44, 'Asia', 'Central Asia', 'Kazakhstan', 2021, 0.73);
INSERT INTO feminicide VALUES (45, 'Asia', 'Central Asia', 'Ouzbékistan', 2021, 0.58);
INSERT INTO feminicide VALUES (46, 'Asia', 'Eastern Asia', 'Hong Kong', 2021, 0.15);
INSERT INTO feminicide VALUES (47, 'Asia', 'Eastern Asia', 'Macao', 2021, 0.48);
INSERT INTO feminicide VALUES (48, 'Asia', 'Eastern Asia', 'Japon', 2021, 0.11);
INSERT INTO feminicide VALUES (49, 'Asia', 'Eastern Asia', 'Mongolie', 2021, 1.34);
INSERT INTO feminicide VALUES (50, 'Asia', 'Eastern Asia', 'Corée du Sud', 2021, 0.25);
INSERT INTO feminicide VALUES (51, 'Asia', 'South-eastern Asia', 'Myanmar', 2021, 3.45);
INSERT INTO feminicide VALUES (52, 'Asia', 'South-eastern Asia', 'Singapour', 2021, 0.03);
INSERT INTO feminicide VALUES (53, 'Asia', 'Southern Asia', 'Inde', 2021, 1.27);
INSERT INTO feminicide VALUES (54, 'Asia', 'Western Asia', 'Arménie', 2021, 4.65);
INSERT INTO feminicide VALUES (55, 'Asia', 'Western Asia', 'Azerbaïdjan', 2021, 0.67);
INSERT INTO feminicide VALUES (56, 'Asia', 'Western Asia', 'Bahreïn', 2021, 0.07);
INSERT INTO feminicide VALUES (57, 'Asia', 'Western Asia', 'Chypre', 2021, 0.55);
INSERT INTO feminicide VALUES (58, 'Asia', 'Western Asia', 'Irak', 2021, 0.6);
INSERT INTO feminicide VALUES (59, 'Asia', 'Western Asia', 'Israël', 2021, 0.99);
INSERT INTO feminicide VALUES (60, 'Asia', 'Western Asia', 'Jordanie', 2021, 0.28);
INSERT INTO feminicide VALUES (61, 'Asia', 'Western Asia', 'Oman', 2021, 0.08);
INSERT INTO feminicide VALUES (62, 'Asia', 'Western Asia', 'Qatar', 2021, 0.16);
INSERT INTO feminicide VALUES (63, 'Asia', 'Western Asia', 'Palestine', 2021, 0.31);
INSERT INTO feminicide VALUES (64, 'Asia', 'Western Asia', 'Turquie', 2021, 0.53);
INSERT INTO feminicide VALUES (65, 'Asia', 'Western Asia', 'Émirats arabes unis', 2021, 0.1);
INSERT INTO feminicide VALUES (66, 'Europe', 'Eastern Europe', 'Bulgarie', 2021, 0.4);
INSERT INTO feminicide VALUES (67, 'Europe', 'Eastern Europe', 'Tchéquie', 2021, 0.23);
INSERT INTO feminicide VALUES (68, 'Europe', 'Eastern Europe', 'Hongrie', 2021, 0.27);
INSERT INTO feminicide VALUES (69, 'Europe', 'Eastern Europe', 'Pologne', 2021, 0.21);
INSERT INTO feminicide VALUES (70, 'Europe', 'Eastern Europe', 'Moldavie', 2021, 0.36);
INSERT INTO feminicide VALUES (71, 'Europe', 'Eastern Europe', 'Roumanie', 2021, 0.36);
INSERT INTO feminicide VALUES (72, 'Europe', 'Eastern Europe', 'Russie', 2021, 1.8);
INSERT INTO feminicide VALUES (73, 'Europe', 'Eastern Europe', 'Slovaquie', 2021, 0.33);
INSERT INTO feminicide VALUES (74, 'Europe', 'Northern Europe', 'Danemark', 2021, 0.24);
INSERT INTO feminicide VALUES (75, 'Europe', 'Northern Europe', 'Estonie', 2021, 0.33);
INSERT INTO feminicide VALUES (76, 'Europe', 'Northern Europe', 'Finlande', 2021, 0.48);
INSERT INTO feminicide VALUES (77, 'Europe', 'Northern Europe', 'Islande', 2021, 0.28);
INSERT INTO feminicide VALUES (78, 'Europe', 'Northern Europe', 'Irlande', 2021, 0.13);
INSERT INTO feminicide VALUES (79, 'Europe', 'Northern Europe', 'Lettonie', 2021, 1.93);
INSERT INTO feminicide VALUES (80, 'Europe', 'Northern Europe', 'Lituanie', 2021, 0.81);
INSERT INTO feminicide VALUES (81, 'Europe', 'Northern Europe', 'Norvège', 2021, 0.29);
INSERT INTO feminicide VALUES (82, 'Europe', 'Northern Europe', 'Suède', 2021, 0.23);
INSERT INTO feminicide VALUES (83, 'Europe', 'Northern Europe', 'Royaume-Uni ', 2021, 0.32);
INSERT INTO feminicide VALUES (86, 'Europe', 'Southern Europe', 'Albanie', 2021, 0.39);
INSERT INTO feminicide VALUES (87, 'Europe', 'Southern Europe', 'Bosnie-Herzégovine', 2021, 0.18);
INSERT INTO feminicide VALUES (88, 'Europe', 'Southern Europe', 'Croatie', 2021, 0.33);
INSERT INTO feminicide VALUES (89, 'Europe', 'Southern Europe', 'Grèce', 2021, 0.31);
INSERT INTO feminicide VALUES (90, 'Europe', 'Southern Europe', 'Vatican', 2021, 0.0);
INSERT INTO feminicide VALUES (91, 'Europe', 'Southern Europe', 'Italie', 2021, 0.19);
INSERT INTO feminicide VALUES (92, 'Europe', 'Southern Europe', 'Kosovo', 2021, 0.16);
INSERT INTO feminicide VALUES (93, 'Europe', 'Southern Europe', 'Malte', 2021, 0.0);
INSERT INTO feminicide VALUES (94, 'Europe', 'Southern Europe', 'Monténégro', 2021, 0.33);
INSERT INTO feminicide VALUES (95, 'Europe', 'Southern Europe', 'Macédoine du Nord', 2021, 0.14);
INSERT INTO feminicide VALUES (96, 'Europe', 'Southern Europe', 'Portugal', 2021, 0.24);
INSERT INTO feminicide VALUES (97, 'Europe', 'Southern Europe', 'Serbie', 2021, 0.39);
INSERT INTO feminicide VALUES (98, 'Europe', 'Southern Europe', 'Slovénie', 2021, 0.29);
INSERT INTO feminicide VALUES (99, 'Europe', 'Southern Europe', 'Espagne', 2021, 0.21);
INSERT INTO feminicide VALUES (100, 'Europe', 'Western Europe', 'Autriche', 2021, 0.45);
INSERT INTO feminicide VALUES (101, 'Europe', 'Western Europe', 'Belgique', 2021, 0.6);
INSERT INTO feminicide VALUES (102, 'Europe', 'Western Europe', 'France', 2021, 0.33);
INSERT INTO feminicide VALUES (103, 'Europe', 'Western Europe', 'Allemagne', 2021, 0.42);
INSERT INTO feminicide VALUES (104, 'Europe', 'Western Europe', 'Liechtenstein', 2021, 2.54);
INSERT INTO feminicide VALUES (105, 'Europe', 'Western Europe', 'Pays-Bas', 2021, 0.22);
INSERT INTO feminicide VALUES (106, 'Europe', 'Western Europe', 'Suisse', 2021, 0.3);
INSERT INTO feminicide VALUES (107, 'Oceania', 'Australia and New Zealand', 'Australie', 2021, 0.58);
INSERT INTO feminicide VALUES (108, 'Oceania', 'Australia and New Zealand', 'Nouvelle-Zélande', 2021, 0.3);
